---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  connection: local
  
  tasks:
    - name: Pull the latest image from Docker Hub
      command: docker pull ranag99/spe-mini-project:latest

    - name: Stop the existing calculator container (if it exists)
      command: docker stop calc-container
      ignore_errors: yes 

    - name: Remove the old container
      command: docker rm calc-container
      ignore_errors: yes

    - name: Start the new interactive calculator container
      command: docker run -dit --name calc-container ranag99/spe-mini-project:latest
